// <auto-generated />
using System;
using EasyManager.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EasyManager.Infra.Data.Migrations
{
    [DbContext(typeof(EasyManagerContext))]
    [Migration("20180912180757_ManufactureMigrations")]
    partial class ManufactureMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EasyManager.Domain.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<string>("Address");

                    b.Property<string>("Contacts");

                    b.Property<string>("CorporateTaxpayerId");

                    b.Property<string>("IndividualTaxpayerId");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("EasyManager.Domain.Models.Manufacture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Contacts");

                    b.Property<string>("CorporateTaxpayerId");

                    b.Property<string>("TradeName");

                    b.HasKey("Id");

                    b.ToTable("Manufactures");
                });
#pragma warning restore 612, 618
        }
    }
}
